Screens Added: Python file of screens are added
M-Usman-Tahir/voice-controlled-departmental-noticeboard pull request #9
Opened 2021-12-13 15:45 UTC by ikramali585

2021-12-13 15:58 UTC, M-Usman-Tahir requested changes
### Write down a reason...
- Why did you remove the complete conetnts?
### Expected changes
- Revert the contents...

2021-12-13 16:31 UTC, M-Usman-Tahir reviewed
It won't be readable if the header file is deleted...

2021-12-13 16:31 UTC, M-Usman-Tahir commented on Authentication/LoginRecord.csv
> +
```suggestion
Name,Time,Date

```

2021-12-13 18:17 UTC, ikramali585 commented
I did it mistakenly
How can I revert it?

2021-12-14 08:20 UTC, M-Usman-Tahir requested changes
Change the code according to the following request....

2021-12-14 08:20 UTC, M-Usman-Tahir commented on Authentication/LoginRecord.csv
> +2019-CE-41,16:17:12,12-12-21
### Changes Required...
- Only the first line was required...
- Push it with that commit...

2021-12-14 08:30 UTC, M-Usman-Tahir approved these changes
Approving Views

2021-12-14 08:30 UTC, merged